version: '3.0'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: sakila
      MYSQL_PASSWORD: sakila
    volumes:
      - ./dbdata:/var/lib/mysql
      - ./sakila-db:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    restart: always
  
  mod2lab1:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile_mod2lab1_webapp
    image: mod2lab1_webapp
    container_name: mod2lab1_debug
    volumes:
      - ./:/app
    ports:
      - "80:80"
      - "5000:5000"
      - "5001:5001"